/* Tests for src/manifest.c, checked against the REAL Python yaml_io.dump_manifest()/
 * dump_assets_index() output for the same inputs (captured via `python3 -c "import yaml_io..."`
 * -- see conversation), plus round-trip parsing. */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "manifest.h"

static int all_ok = 1;

static void check(const char *what, int cond) {
    printf("[%s] %s\n", cond ? "OK" : "FAIL", what);
    all_ok &= cond;
}

/* Exact byte-for-byte output of Python's dump_manifest() for this same two-game manifest
 * (captured directly from Injector/assetbind/yaml_io.py, not retyped by hand). */
static const char *EXPECTED_MANIFEST =
    "version: 1\n"
    "games:\n"
    "  - game_id: \"abc123\"\n"
    "    identity:\n"
    "      sha1: \"abc123\"\n"
    "      md5: \"def456\"\n"
    "      crc32: \"deadbeef\"\n"
    "      size: 1048576\n"
    "    rom_name: \"My Game (USA).nds\"\n"
    "    assets:\n"
    "      logo: \"assets/abc123/logo.png\"\n"
    "      video: null\n"
    "      video_top: \"assets/abc123/top.tgrv\"\n"
    "      video_bottom: \"assets/abc123/bottom.tgrv\"\n"
    "  - game_id: \"xyz789\"\n"
    "    identity:\n"
    "      sha1: \"xyz\"\n"
    "      md5: \"\"\n"
    "      crc32: \"\"\n"
    "      size: 0\n"
    "    assets:\n"
    "      logo: null\n"
    "      video: null\n"
    "      video_top: null\n"
    "      video_bottom: null\n";

static const char *EXPECTED_ASSETS_INDEX =
    "# GENERATED by the host: base name on the SD (no extension) -> game_id.\n"
    "# The DS matches the focused ROM here and loads assets/<game_id>/.\n"
    "version: 1\n"
    "roms:\n"
    "  \"Dup Game.nds\": \"gid1\"\n"
    "  \"Game A.nds\": \"gid1\"\n"
    "  \"Game B.nds\": \"gid2\"\n";

int main(void) {
    /* 1. manifest_dump() must match Python's dump_manifest() byte-for-byte. */
    {
        Manifest m;
        manifest_init(&m);

        ManifestGame *g1 = manifest_add_game(&m);
        g1->game_id = strdup("abc123");
        snprintf(g1->identity.sha1, sizeof(g1->identity.sha1), "abc123");
        snprintf(g1->identity.md5, sizeof(g1->identity.md5), "def456");
        snprintf(g1->identity.crc32, sizeof(g1->identity.crc32), "deadbeef");
        g1->identity.size = 1048576;
        g1->rom_name = strdup("My Game (USA).nds");
        g1->logo = strdup("assets/abc123/logo.png");
        g1->video = NULL;
        g1->video_top = strdup("assets/abc123/top.tgrv");
        g1->video_bottom = strdup("assets/abc123/bottom.tgrv");

        ManifestGame *g2 = manifest_add_game(&m);
        g2->game_id = strdup("xyz789");
        snprintf(g2->identity.sha1, sizeof(g2->identity.sha1), "xyz");
        /* md5/crc32 left as empty strings, size left 0 -- matches the Python test input. */

        char *dump = manifest_dump(&m);
        check("manifest_dump matches Python dump_manifest() exactly",
              strcmp(dump, EXPECTED_MANIFEST) == 0);
        if (strcmp(dump, EXPECTED_MANIFEST) != 0) {
            printf("--- got ---\n%s--- want ---\n%s", dump, EXPECTED_MANIFEST);
        }

        /* 2. Round-trip: parse what we just dumped, verify it comes back out the same. */
        Manifest loaded;
        manifest_load(dump, &loaded);
        check("round-trip: game_count == 2", loaded.game_count == 2);
        if (loaded.game_count == 2) {
            check("round-trip: game 1 id", strcmp(loaded.games[0].game_id, "abc123") == 0);
            check("round-trip: game 1 sha1", strcmp(loaded.games[0].identity.sha1, "abc123") == 0);
            check("round-trip: game 1 md5", strcmp(loaded.games[0].identity.md5, "def456") == 0);
            check("round-trip: game 1 size", loaded.games[0].identity.size == 1048576);
            check("round-trip: game 1 rom_name", loaded.games[0].rom_name &&
                  strcmp(loaded.games[0].rom_name, "My Game (USA).nds") == 0);
            check("round-trip: game 1 logo", loaded.games[0].logo &&
                  strcmp(loaded.games[0].logo, "assets/abc123/logo.png") == 0);
            check("round-trip: game 1 video is NULL", loaded.games[0].video == NULL);
            check("round-trip: game 1 video_top", loaded.games[0].video_top &&
                  strcmp(loaded.games[0].video_top, "assets/abc123/top.tgrv") == 0);

            check("round-trip: game 2 id", strcmp(loaded.games[1].game_id, "xyz789") == 0);
            check("round-trip: game 2 rom_name absent -> NULL", loaded.games[1].rom_name == NULL);
            check("round-trip: game 2 logo is NULL", loaded.games[1].logo == NULL);
            check("round-trip: game 2 md5 empty string", strcmp(loaded.games[1].identity.md5, "") == 0);
        }

        free(dump);
        manifest_free(&loaded);
        manifest_free(&m);
    }

    /* 3. assets_index_dump() must match Python's dump_assets_index() exactly, including sorting
     * and duplicate rom_names pointing at the same game_id. */
    {
        AssetsIndex idx;
        assets_index_init(&idx);
        assets_index_set(&idx, "Game B.nds", "gid2");
        assets_index_set(&idx, "Game A.nds", "gid1");
        assets_index_set(&idx, "Dup Game.nds", "gid1");

        char *dump = assets_index_dump(&idx);
        check("assets_index_dump matches Python dump_assets_index() exactly",
              strcmp(dump, EXPECTED_ASSETS_INDEX) == 0);
        if (strcmp(dump, EXPECTED_ASSETS_INDEX) != 0) {
            printf("--- got ---\n%s--- want ---\n%s", dump, EXPECTED_ASSETS_INDEX);
        }

        AssetsIndex loaded;
        assets_index_load(dump, &loaded);
        check("assets_index round-trip: count == 3", loaded.count == 3);

        int found_a = 0, found_b = 0, found_dup = 0;
        for (size_t i = 0; i < loaded.count; i++) {
            if (strcmp(loaded.entries[i].rom_name, "Game A.nds") == 0 &&
                strcmp(loaded.entries[i].game_id, "gid1") == 0) found_a = 1;
            if (strcmp(loaded.entries[i].rom_name, "Game B.nds") == 0 &&
                strcmp(loaded.entries[i].game_id, "gid2") == 0) found_b = 1;
            if (strcmp(loaded.entries[i].rom_name, "Dup Game.nds") == 0 &&
                strcmp(loaded.entries[i].game_id, "gid1") == 0) found_dup = 1;
        }
        check("assets_index round-trip: Game A.nds -> gid1", found_a);
        check("assets_index round-trip: Game B.nds -> gid2", found_b);
        check("assets_index round-trip: Dup Game.nds -> gid1 (shared game_id)", found_dup);

        free(dump);
        assets_index_free(&loaded);
        assets_index_free(&idx);
    }

    printf(all_ok ? "\nALL TESTS PASSED\n" : "\nSOME TESTS FAILED\n");
    return all_ok ? 0 : 1;
}
